language: php
env:
  global:
  - WEB_PORT_80_TCP_ADDR=localhost
  - secure: p2TLxrOfl7xFRhur6Lga5GWxrOr+/+msF3VGqDkNYFTGiGhEWIFel+oaYjcsQL4VQGVpYiIEbMTqXlTWT7cMpUcong0XqWM9C8uMIspy74lvCy/+ypPGwYgs8DyHUbPyF89sWjKPKr6ivlXxWR93RgCdjwa4QanHENUt9pRbJAQX7Zy1Fu7sCpkeu4lgo0zJyFcaxvcQZsknmkLSE6sFG2CGd0JtC1UZstfvzwlBLR6UrNsTLFzzUY3DezZbjraXqbkMXMnEibLgHiPWgL2fBGZkvOZFdc6g61oPEM9CRHuLj3HngCnF86E5S3kHP8iZuO4S6uAjWqZ4LL5mhiAVN3lb3erAC7hXAhr2g13RNI8PDUvaZd53/S580jzxRffWb7LPuitYLI/pRqD3pNAltiRUJaq2BTcW6YCR5PUPStLrkE0HDTB7++i+r4fgukdLp9KtIEejIK6eI8s/z1pwV3dlYg1bJl8h2eA6ATvOz20x8lh0gbfcDYZekMJCdo8Wt9XKluYp24cTwE7wZucYLpMBqT7EddpdbkckTpntRuBjMqJamwlX2sDtWvyjd2AG+v18uZHZbNTjRFbYQioskvJ8L4sYMtJOek8aPiB0iU3J80mtWdy3CXEDvE+xSsNeQq3A3y2lK5IW+yObZFiUbClm6JHeq6dopH3HC2A1c+g=

matrix:
  include:
    - php: 7.0
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
sudo: required
dist: trusty
cache:
  - apt
addons:
  apt:
    packages:
      - realpath
      - mailutils
install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras
  #- travis-ci/install-nginx2.sh
script:
  - travis-ci/install-nginx2.sh
  - curl -vsf 'http://localhost:9000/index.php' &> /dev/stdout
  - curl -A "googlebot" http://localhost:9000/index.php &> /dev/stdout
  #- cat /tmp/error.log
  - STATUSCODE=$(curl -A "80legs" http://localhost:9000/index.php &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
  - STATUSCODE=$(curl -A "masscan" http://localhost:9000/index.php &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
  - STATUSCODE=$(curl -I http://localhost:9000/index.php -e http://100dollars-seo.com &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
  - STATUSCODE=$(curl -I http://localhost:9000/index.php -e http://zx6.ru &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi

before_deploy:
#- git remote add origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
#- git config --global user.email "${GIT_EMAIL}"
#- git config --global user.name "${GIT_NAME}"
#- git config --global push.default simple
- export GIT_TAG=v1.0.$TRAVIS_BUILD_NUMBER
#- sudo $TRAVIS_BUILD_DIR/travis-ci/modify-globalblacklist.sh
#- cat $TRAVIS_BUILD_DIR/globalblacklist.conf
#- git commit -am "Travis Test Passed"
#- git commit -a
- git add .
- git tag $GIT_TAG -a -m "Tag Generated from TravisCI for build $TRAVIS_BUILD_NUMBER"
#- git push origin master && git push origin master --tags
- git push https://${GH_TOKEN}@github.com/mitchellkrogza/Travis-CI-Nginx-for-Testing-Nginx-Configuration --tags
- ls -aR
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - test.txt
  - test2.txt
  - globalblacklist.conf
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
notifications:
  email: false