language: php

env:
- WEB_PORT_80_TCP_ADDR=localhost

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - realpath

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras
  - travis-ci/install-nginx.sh

script:
  - sudo nginx -t &> /dev/stdout
  - curl -vsf 'http://localhost:8080/nginx.php' &> /dev/stdout
  - curl -A "googlebot" http://localhost:8080/nginx.php &> /dev/stdout
  - cat /tmp/error.log